"use strict";

const TOOL_NAMES = [
  "clone_slideshow_event_tree",
  "extend_slideshow_cloned_tree",
  "rewrite_slideshow_tree_expressions",
  "apply_slideshow_event_text",
  "replace_slideshow_media_leaf",
  "copy_slideshow_event_pair",
  "add_slideshow_event_overlays",
  "copy_slideshow_control_layer",
  "audit_slideshow_generated",
  "configure_slideshow_tree_audio",
  "create_slideshow_master"
];
const STRUCTURE_SCHEMA = "ae-agent-comp-structure.v1";

function fail(message) { const error = new Error(message); error.code = "INVALID_SLIDESHOW_TOOL_INPUT"; throw error; }
function plain(value, label) { if (!value || typeof value !== "object" || Array.isArray(value)) fail(`${label} must be an object.`); return value; }
function only(value, keys, label) { const extra = Object.keys(value).find((key) => !keys.includes(key)); if (extra) fail(`${label}.${extra} is not supported.`); }
function text(value, label, max = 2048) { if (typeof value !== "string" || !value.trim() || value.length > max) fail(`${label} must be a non-empty string up to ${max} characters.`); return value.trim(); }
function num(value, label, min = -Infinity) { if (typeof value !== "number" || !Number.isFinite(value) || value < min) fail(`${label} must be a finite number >= ${min}.`); return value; }
function int(value, label) { const result = num(value, label, 1); if (!Number.isInteger(result)) fail(`${label} must be an integer.`); return result; }
function optionalIndex(value, label) { return value === undefined ? null : int(value, label); }
function bool(value, label) { if (typeof value !== "boolean") fail(`${label} must be boolean.`); return value; }
function literal(value) { return JSON.stringify(value).replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029"); }
function generated(value, prefix, label) { const result = text(value, label, 180); if (!result.startsWith(prefix)) fail(`${label} must start with generatedPrefix.`); if(/["'\\\r\n]/.test(result))fail(`${label} contains a forbidden quote, slash, or newline.`); return result; }
function nullableText(value,label,max=180){return value===null?null:text(value,label,max);}
function nullableInt(value,label){return value===null?null:int(value,label);}
function structureLayer(value,label){
  plain(value,label);only(value,["layerId","name","sourceType","sourceItemId","sourceName","startTime","inPoint","outPoint","stretch","enabled","audioEnabled","timeRemapEnabled","guideLayer","adjustmentLayer","threeDLayer","collapseTransformation"],label);
  const sourceType=text(value.sourceType,`${label}.sourceType`,20);if(!["comp","footage","none"].includes(sourceType))fail(`${label}.sourceType must be comp, footage, or none.`);
  const row={layerId:int(value.layerId,`${label}.layerId`),name:text(value.name,`${label}.name`,180),sourceType,sourceItemId:nullableInt(value.sourceItemId,`${label}.sourceItemId`),sourceName:nullableText(value.sourceName,`${label}.sourceName`,180),startTime:num(value.startTime,`${label}.startTime`),inPoint:num(value.inPoint,`${label}.inPoint`),outPoint:num(value.outPoint,`${label}.outPoint`),stretch:num(value.stretch,`${label}.stretch`),enabled:bool(value.enabled,`${label}.enabled`),audioEnabled:bool(value.audioEnabled,`${label}.audioEnabled`),timeRemapEnabled:bool(value.timeRemapEnabled,`${label}.timeRemapEnabled`),guideLayer:bool(value.guideLayer,`${label}.guideLayer`),adjustmentLayer:bool(value.adjustmentLayer,`${label}.adjustmentLayer`),threeDLayer:bool(value.threeDLayer,`${label}.threeDLayer`),collapseTransformation:bool(value.collapseTransformation,`${label}.collapseTransformation`)};
  if(sourceType==="none"&&(row.sourceItemId!==null||row.sourceName!==null))fail(`${label} none source must use null source identity.`);if(sourceType!=="none"&&(row.sourceItemId===null||row.sourceName===null))fail(`${label} source identity is required.`);return row;
}
function sourceFingerprint(value,label,requireStructure){
  plain(value,label);only(value,["itemIndex","itemId","name","duration","numLayers","structureSchema","layers"],label);
  const row={itemIndex:optionalIndex(value.itemIndex,`${label}.itemIndex`),itemId:value.itemId===undefined||value.itemId===null?null:int(value.itemId,`${label}.itemId`),name:text(value.name,`${label}.name`,180),duration:num(value.duration,`${label}.duration`,0.001),numLayers:positiveWhole(value.numLayers,`${label}.numLayers`),structureSchema:value.structureSchema===undefined?null:text(value.structureSchema,`${label}.structureSchema`,80),layers:null};
  if(value.layers!==undefined){if(!Array.isArray(value.layers)||value.layers.length>1000)fail(`${label}.layers must contain at most 1000 entries.`);row.layers=value.layers.map((layer,index)=>structureLayer(layer,`${label}.layers[${index}]`));}
  const complete=row.itemId!==null&&row.structureSchema===STRUCTURE_SCHEMA&&Array.isArray(row.layers)&&row.layers.length===row.numLayers;
  if(requireStructure&&!complete)fail(`${label} must contain itemId, ${STRUCTURE_SCHEMA}, and one structural row per layer.`);return row;
}
function sourceFingerprints(value,label,requireStructure){if(!Array.isArray(value)||value.length>30)fail(`${label} must contain at most 30 entries.`);return value.map((item,index)=>sourceFingerprint(item,`${label}[${index}]`,requireStructure));}

function checkpointProperties(checkpoint) { return checkpoint || {}; }
function schema(properties, required, checkpoint) {
  return { type: "object", additionalProperties: false, properties: { ...properties, ...checkpointProperties(checkpoint) }, required };
}

function createToolDefinitions(checkpoint) {
  const structuralLayer={type:"object",additionalProperties:false,properties:{layerId:{type:"number",minimum:1},name:{type:"string"},sourceType:{type:"string",enum:["comp","footage","none"]},sourceItemId:{type:["number","null"],minimum:1},sourceName:{type:["string","null"]},startTime:{type:"number"},inPoint:{type:"number"},outPoint:{type:"number"},stretch:{type:"number"},enabled:{type:"boolean"},audioEnabled:{type:"boolean"},timeRemapEnabled:{type:"boolean"},guideLayer:{type:"boolean"},adjustmentLayer:{type:"boolean"},threeDLayer:{type:"boolean"},collapseTransformation:{type:"boolean"}},required:["layerId","name","sourceType","sourceItemId","sourceName","startTime","inPoint","outPoint","stretch","enabled","audioEnabled","timeRemapEnabled","guideLayer","adjustmentLayer","threeDLayer","collapseTransformation"]};
  const fingerprint={type:"object",additionalProperties:false,properties:{itemIndex:{type:"number",minimum:1},itemId:{type:"number",minimum:1},name:{type:"string"},duration:{type:"number"},numLayers:{type:"number",minimum:0},structureSchema:{type:"string",enum:[STRUCTURE_SCHEMA]},layers:{type:"array",maxItems:1000,items:structuralLayer}},required:["name","duration","numLayers"]};
  const identity = {
    expectedProjectFile: { type: "string", description: "Exact saved AE project path guard." },
    generatedPrefix: { type: "string", pattern: "^CODX_[A-Z0-9_-]+_$", description: "Generated item namespace." },
    protectedSourceFingerprints:{type:"array",maxItems:30,items:fingerprint,description:"Accepted operation baseline for protected source compositions; complete v1 structure is required when supplied."}
  };
  return [
    { name: TOOL_NAMES[0], description: "Clone one source scene tree into an isolated generated namespace and relink only the cloned precomp layers, with explicit preserved or muted clone audio. The exact unique name is authoritative; sourceCompItemIndex is an optional current-index guard.", inputSchema: schema({ ...identity, sourceCompItemIndex: {type:"number",minimum:1}, expectedSourceCompName:{type:"string"}, generatedRootName:{type:"string"}, audioMode:{type:"string",enum:["preserve","mute"]} }, ["expectedProjectFile","generatedPrefix","expectedSourceCompName","generatedRootName"], checkpoint) },
    { name: TOOL_NAMES[1], description: "Extend one generated clone tree, preserving temporal/spatial key metadata and tiling finite footage at 1x speed. The exact unique name and owner marker are authoritative; rootCompItemIndex is an optional current-index guard.", inputSchema: schema({ ...identity, rootCompItemIndex:{type:"number",minimum:1}, expectedRootCompName:{type:"string"}, targetDuration:{type:"number"}, introDuration:{type:"number"} }, ["expectedProjectFile","generatedPrefix","expectedRootCompName","targetDuration","introDuration"], checkpoint) },
    { name: TOOL_NAMES[2], description: "Rewrite only explicit composition references across a generated slideshow tree.", inputSchema: schema({ ...identity, rootCompItemIndex:{type:"number",minimum:1}, expectedRootCompName:{type:"string"}, masterCompName:{type:"string"}, replacements:{type:"array",maxItems:40,items:{type:"object",additionalProperties:false,properties:{from:{type:"string"},to:{type:"string"}},required:["from","to"]}} }, ["expectedProjectFile","generatedPrefix","expectedRootCompName","masterCompName","replacements"], checkpoint) },
    { name: TOOL_NAMES[3], description: "Apply deterministic title and newspaper article styling inside one generated slideshow tree.", inputSchema: schema({ ...identity, rootCompItemIndex:{type:"number",minimum:1}, expectedRootCompName:{type:"string"}, sceneNumber:{type:"number"}, titleCompName:{type:"string"}, hero:{type:"string",enum:["suhanov","kurnikov","both"]}, title:{type:"string"}, titleWrap:{type:"number"}, articleChunks:{type:"array",minItems:1,maxItems:20,items:{type:"string"}} }, ["expectedProjectFile","generatedPrefix","expectedRootCompName","sceneNumber","titleCompName","hero","title","titleWrap","articleChunks"], checkpoint) },
    { name: TOOL_NAMES[4], description: "Create a clean generated media leaf, add explicit media at 1x speed, and relink matching generated-tree layers without deleting template layers.", inputSchema: schema({ ...identity, rootCompItemIndex:{type:"number",minimum:1}, expectedRootCompName:{type:"string"}, leafName:{type:"string"}, generatedLeafName:{type:"string"}, duration:{type:"number"}, mediaItems:{type:"array",minItems:1,maxItems:24,items:{type:"object",additionalProperties:false,properties:{path:{type:"string"},start:{type:"number"},duration:{type:"number"},sourceIn:{type:"number"},audio:{type:"boolean"}},required:["path","start","duration","sourceIn","audio"]}} }, ["expectedProjectFile","generatedPrefix","expectedRootCompName","leafName","generatedLeafName","duration","mediaItems"], checkpoint) },
    { name: TOOL_NAMES[5], description: "Copy the guarded intro/main scene layer pair into the generated master after exact source effect-count preflight, preserving copied effects and assigning event timing.", inputSchema: schema({ ...identity, finalCompItemIndex:{type:"number",minimum:1},expectedFinalCompName:{type:"string"},masterCompItemIndex:{type:"number",minimum:1},expectedMasterCompName:{type:"string"},rootCompItemIndex:{type:"number",minimum:1},expectedRootCompName:{type:"string"},sourceSceneName:{type:"string"},sceneNumber:{type:"number"},eventStart:{type:"number"},eventDuration:{type:"number"},introDuration:{type:"number"},rootHasAudio:{type:"boolean"},introEffectCount:{type:"number",minimum:0},mainEffectCount:{type:"number",minimum:0} }, ["expectedProjectFile","generatedPrefix","expectedFinalCompName","expectedMasterCompName","expectedRootCompName","sourceSceneName","sceneNumber","eventStart","eventDuration","introDuration","rootHasAudio","introEffectCount","mainEffectCount"], checkpoint) },
    { name: TOOL_NAMES[6], description: "Add bounded audio-only footage and newspaper captions for one slideshow event.", inputSchema: schema({ ...identity, masterCompItemIndex:{type:"number",minimum:1},expectedMasterCompName:{type:"string"},eventId:{type:"string"},eventStart:{type:"number"},eventDuration:{type:"number"},audioItems:{type:"array",maxItems:24,items:{type:"object",additionalProperties:false,properties:{path:{type:"string"},start:{type:"number"},duration:{type:"number"},sourceIn:{type:"number"},audio:{type:"boolean"}},required:["path","start","duration","sourceIn","audio"]}},captions:{type:"array",maxItems:8,items:{type:"string"}} }, ["expectedProjectFile","generatedPrefix","expectedMasterCompName","eventId","eventStart","eventDuration","audioItems","captions"], checkpoint) },
    { name: TOOL_NAMES[7], description: "Copy one explicitly named CONTROL or COLOR source layer to the same explicit role in a generated master after exact source effect-count preflight.", inputSchema: schema({ ...identity, sourceCompItemIndex:{type:"number",minimum:1},expectedSourceCompName:{type:"string"},sourceLayerName:{type:"string"},targetLayerName:{type:"string",enum:["CONTROL","COLOR"]},expectedEffectCount:{type:"number",minimum:0},masterCompItemIndex:{type:"number",minimum:1},expectedMasterCompName:{type:"string"},duration:{type:"number"} }, ["expectedProjectFile","generatedPrefix","expectedSourceCompName","sourceLayerName","expectedEffectCount","expectedMasterCompName","duration"], checkpoint) },
    { name: TOOL_NAMES[8], description: "Read-only audit of a generated slideshow tree, event coverage, key metadata, audio/video switches, effects, and protected source fingerprints.", inputSchema: schema({ ...identity, rootCompItemIndex:{type:"number",minimum:1},expectedRootCompName:{type:"string"},expectedDuration:{type:"number"},sourceFingerprints:{type:"array",maxItems:30,items:fingerprint},sourceCompItemIndex:{type:"number",minimum:1},sourceCompItemId:{type:"number",minimum:1},expectedSourceCompName:{type:"string"},expectedSourceDuration:{type:"number"},expectedSourceNumLayers:{type:"number"} }, ["expectedProjectFile","generatedPrefix","expectedRootCompName","expectedDuration","sourceFingerprints"], {}) },
    { name: TOOL_NAMES[9], description: "Dedupe audible precomp routes in one generated tree while preserving explicitly audible media leaves.", inputSchema: schema({ ...identity, rootCompItemIndex:{type:"number",minimum:1},expectedRootCompName:{type:"string"} }, ["expectedProjectFile","generatedPrefix","expectedRootCompName"], checkpoint) },
    { name: TOOL_NAMES[10], description: "Create one collision-guarded generated slideshow master with an ownership marker and background layer.", inputSchema: schema({ ...identity, masterName:{type:"string"},width:{type:"number"},height:{type:"number"},pixelAspect:{type:"number"},duration:{type:"number"},frameRate:{type:"number"},backgroundColor:{type:"array",minItems:3,maxItems:3,items:{type:"number"}} }, ["expectedProjectFile","generatedPrefix","masterName","width","height","pixelAspect","duration","frameRate","backgroundColor"], checkpoint) }
  ];
}

function common(args, allowed) {
  plain(args, "args"); only(args, [...allowed,"protectedSourceFingerprints"], "args");
  const expectedProjectFile = text(args.expectedProjectFile, "expectedProjectFile", 2048);
  const generatedPrefix = text(args.generatedPrefix, "generatedPrefix", 80);
  if (!/^CODX_[A-Z0-9_-]+_$/.test(generatedPrefix)) fail("generatedPrefix must match CODX_*_.");
  const protectedSourceFingerprints=args.protectedSourceFingerprints===undefined?[]:sourceFingerprints(args.protectedSourceFingerprints,"protectedSourceFingerprints",true);
  return { expectedProjectFile, generatedPrefix, protectedSourceFingerprints };
}

function prelude(data) {
  return String.raw`var __d=${literal(data)};
if(!app.project||!app.project.file)throw new Error("saved_project_required");
function __norm(v){return String(v||"").replace(/\\/g,"/").toLowerCase();}
if(__norm(app.project.file.fsName)!==__norm(__d.expectedProjectFile))throw new Error("project_target_mismatch");
function __item(i,n){var found=null,count=0;for(var ii=1;ii<=app.project.numItems;ii++){var candidate=app.project.item(ii);if(candidate instanceof CompItem&&candidate.name===n){found=candidate;count++;}}if(count!==1)throw new Error("composition_identity_mismatch:"+n+":"+count);if(i!==null&&i!==undefined&&app.project.item(i)!==found)throw new Error("composition_index_mismatch:"+n+":"+i);return found;}
function __idx(x){for(var i=1;i<=app.project.numItems;i++)if(app.project.item(i)===x)return i;return null;}
function __stableId(x){if(!x||typeof x.id!=="number")throw new Error("stable_item_id_unavailable:"+(x?x.name:"missing"));return Number(x.id);}
function __key(x){return "id:"+__stableId(x);}
function __owner(){return "AE_AGENT_SLIDESHOW:"+__d.generatedPrefix+":"+(__d.ownerRootName||__d.expectedRootCompName||__d.generatedRootName||"");}
function __ownerRoot(x){var marker="AE_AGENT_SLIDESHOW:"+__d.generatedPrefix+":",comment=String(x&&x.comment||"");if(comment.indexOf(marker)!==0)return null;var tail=comment.substring(marker.length),cut=tail.indexOf("|");if(cut>=0)tail=tail.substring(0,cut);return tail||null;}
function __generatedAs(x,ownerRoot){if(!x||x.name.indexOf(__d.generatedPrefix)!==0)throw new Error("generated_scope_required");var actual=__ownerRoot(x);if(!actual)throw new Error("generated_owner_marker_required:"+x.name);if(actual!==ownerRoot)throw new Error("generated_owner_mismatch:"+x.name+":"+actual+":"+ownerRoot);return x;}
function __generated(x){return __generatedAs(x,__d.ownerRootName||__d.expectedRootCompName||__d.generatedRootName||"");}
function __walk(root,fn){var seen={},ordered=[];function inspect(c){var id=__key(c);if(seen[id])return;seen[id]=true;var actual=__ownerRoot(c),expected=__d.ownerRootName||__d.expectedRootCompName||__d.generatedRootName||"";if(c.name.indexOf(__d.generatedPrefix)===0){if(!actual)throw new Error("mutation_scope_provenance_ambiguous:"+c.name);if(actual!==expected)throw new Error("mutation_scope_owner_mismatch:"+c.name+":"+actual+":"+expected);ordered.push(c);}else return;for(var i=1;i<=c.numLayers;i++){var s=c.layer(i).source;if(s instanceof CompItem)inspect(s);}}inspect(root);for(var oi=0;oi<ordered.length;oi++)fn(ordered[oi]);}
function __walkRead(root,fn,dependencies){var seen={};function inspect(c){var id=__key(c);if(seen[id])return;seen[id]=true;fn(c);for(var i=1;i<=c.numLayers;i++){var s=c.layer(i).source;if(!(s instanceof CompItem))continue;var actual=__ownerRoot(s),expected=__d.ownerRootName||__d.expectedRootCompName||__d.generatedRootName||"";if(s.name.indexOf(__d.generatedPrefix)===0&&actual===expected)inspect(s);else dependencies.push({itemIndex:__idx(s),itemId:__stableId(s),name:s.name,ownerRoot:actual,access:"read_only",reason:s.name.indexOf(__d.generatedPrefix)!==0?"external_name":(actual?"different_owner":"ambiguous_provenance")});}}inspect(root);}
function __layerStructure(l){var source=l.source,sourceType="none",sourceItemId=null,sourceName=null;if(source instanceof CompItem){sourceType="comp";sourceItemId=__stableId(source);sourceName=source.name;}else if(source instanceof FootageItem){sourceType="footage";sourceItemId=__stableId(source);sourceName=source.name;}if(typeof l.id!=="number")throw new Error("stable_layer_id_unavailable:"+l.name);return {layerId:Number(l.id),name:String(l.name),sourceType:sourceType,sourceItemId:sourceItemId,sourceName:sourceName,startTime:Number(l.startTime),inPoint:Number(l.inPoint),outPoint:Number(l.outPoint),stretch:l instanceof AVLayer?Number(l.stretch):100,enabled:!!l.enabled,audioEnabled:l.hasAudio?!!l.audioEnabled:false,timeRemapEnabled:l instanceof AVLayer?!!l.timeRemapEnabled:false,guideLayer:!!l.guideLayer,adjustmentLayer:!!l.adjustmentLayer,threeDLayer:!!l.threeDLayer,collapseTransformation:!!l.collapseTransformation};}
function __structure(c){var layers=[];for(var i=1;i<=c.numLayers;i++)layers.push(__layerStructure(c.layer(i)));return {itemId:__stableId(c),name:c.name,duration:Number(c.duration),numLayers:c.numLayers,structureSchema:"${STRUCTURE_SCHEMA}",layers:layers};}
function __digestText(value){var text=JSON.stringify(value),hash=2166136261;for(var i=0;i<text.length;i++){hash^=text.charCodeAt(i);hash+=(hash<<1)+(hash<<4)+(hash<<7)+(hash<<8)+(hash<<24);}return ("00000000"+(hash>>>0).toString(16)).slice(-8);}
function __findByStableId(id){var found=null,count=0;for(var i=1;i<=app.project.numItems;i++){var item=app.project.item(i);if(item instanceof CompItem&&typeof item.id==="number"&&Number(item.id)===Number(id)){found=item;count++;}}return count===1?found:null;}
function __fingerprintSummary(value){return {itemId:value.itemId,name:value.name,duration:value.duration,numLayers:value.numLayers,structureSchema:value.structureSchema,digest:value.structureSchema==="${STRUCTURE_SCHEMA}"&&value.layers instanceof Array?__digestText({itemId:value.itemId,name:value.name,duration:value.duration,numLayers:value.numLayers,structureSchema:value.structureSchema,layers:value.layers}):null};}
function __compareFingerprint(expected){var complete=expected&&typeof expected.itemId==="number"&&expected.structureSchema==="${STRUCTURE_SCHEMA}"&&expected.layers instanceof Array&&expected.layers.length===expected.numLayers;if(!complete)return {expected:__fingerprintSummary(expected||{}),actual:null,unchanged:false,reason:"structural_baseline_missing"};var source=__findByStableId(expected.itemId);if(!source)return {expected:__fingerprintSummary(expected),actual:null,unchanged:false,reason:"stable_source_identity_missing"};var actual=__structure(source),expectedSummary=__fingerprintSummary(expected),actualSummary=__fingerprintSummary(actual),same=JSON.stringify({itemId:expected.itemId,name:expected.name,duration:expected.duration,numLayers:expected.numLayers,structureSchema:expected.structureSchema,layers:expected.layers})===JSON.stringify(actual);return {expected:expectedSummary,actual:actualSummary,unchanged:same,reason:same?null:"structural_mismatch"};}
function __assertSourceFingerprints(values){for(var i=0;i<values.length;i++){var result=__compareFingerprint(values[i]);if(!result.unchanged)throw new Error("protected_source_baseline_stale:"+String(values[i].name||"unknown")+":"+result.reason);}}
function __propertyPathEntry(p,index){return {propertyIndex:typeof p.propertyIndex==="number"?Number(p.propertyIndex):Number(index),matchName:String(p.matchName||""),name:String(p.name||p.matchName||"")};}
function __propertyIdentity(c,l,path){var parts=["comp:"+__stableId(c),"layer:"+__stableId(l)];for(var i=0;i<path.length;i++)parts.push("property:"+path[i].propertyIndex+":"+encodeURIComponent(path[i].matchName)+":"+encodeURIComponent(path[i].name));return parts.join("/");}
function __typedKeyValue(p,keyIndex,identity){var value=p.keyValue(keyIndex);if(typeof value==="number"&&isFinite(value))return {type:"scalar",value:Number(value)};var vectorLike=value&&typeof value==="object"&&typeof value.length==="number";if(vectorLike&&value.length>=1&&value.length<=4){var vector=[];for(var i=0;i<value.length;i++){if(typeof value[i]!=="number"||!isFinite(value[i]))throw new Error("unsupported_key_value:"+identity+":"+keyIndex);vector.push(Number(value[i]));}return {type:"vector",value:vector};}throw new Error("unsupported_key_value:"+identity+":"+keyIndex);}
function __clear(p){if(!p)return;if(p.canSetExpression&&p.expression)p.expression="";while(p.numKeys)p.removeKey(1);}
function __exprDouble(v){return "\""+String(v).replace(/\\/g,"\\\\").replace(/"/g,"\\\"")+"\"";}
function __exprSingle(v){return "'"+String(v).replace(/\\/g,"\\\\").replace(/'/g,"\\'")+"'";}
function __safeGeneratedName(v){return String(v).replace(/["'\\\r\n]/g,"_");}
function __zeroShutter(l){var fx=l.property("ADBE Effect Parade");if(!fx)return 0;var n=0;for(var i=1;i<=fx.numProperties;i++){var e=fx.property(i);if(e.matchName!=="ADBE Geometry2")continue;var use=e.property("ADBE Geometry2-0009"),sh=e.property("ADBE Geometry2-0010");if(use){__clear(use);use.setValue(0);}if(sh){__clear(sh);sh.setValue(0);n++;}}return n;}
function __copyLayerToComp(sourceLayer,targetComp){if(!sourceLayer||typeof sourceLayer.id!=="number")throw new Error("stable_source_layer_id_unavailable");var before={},beforeCount=targetComp.numLayers;for(var bi=1;bi<=beforeCount;bi++){var existing=targetComp.layer(bi);if(!existing||typeof existing.id!=="number")throw new Error("stable_target_layer_id_unavailable:"+bi);before["id:"+existing.id]=true;}sourceLayer.copyToComp(targetComp);if(targetComp.numLayers!==beforeCount+1)throw new Error("copy_layer_count_mismatch");var copied=null,newCount=0;for(var ai=1;ai<=targetComp.numLayers;ai++){var candidate=targetComp.layer(ai);if(!candidate||typeof candidate.id!=="number")throw new Error("stable_copied_layer_id_unavailable:"+ai);if(!before["id:"+candidate.id]){copied=candidate;newCount++;}}if(newCount!==1)throw new Error("copied_layer_identity_mismatch:"+newCount);return copied;}
function __footage(path){for(var i=1;i<=app.project.numItems;i++){var x=app.project.item(i);try{if(x instanceof FootageItem&&x.file&&__norm(x.file.fsName)===__norm(path))return x;}catch(e){}}var f=new File(path);if(!f.exists)throw new Error("media_file_missing:"+path);return app.project.importFile(new ImportOptions(f));}
__assertSourceFingerprints(__d.protectedSourceFingerprints||[]);
`;
}

function cloneScript(d) {
  return prelude(d)+`
var source=__item(__d.sourceCompItemIndex,__d.expectedSourceCompName),desired={},desiredNames={},vis={};function preflight(src,isRoot){var key=__key(src);if(vis[key])return;vis[key]=true;var n=isRoot?__d.generatedRootName:__safeGeneratedName(__d.generatedPrefix+"EV_"+__d.eventToken+"__"+src.name);if(desiredNames["$"+n]&&desiredNames["$"+n]!==key)throw new Error("generated_name_collision:"+n);desiredNames["$"+n]=key;desired[key]=n;for(var p=1;p<=app.project.numItems;p++)if(app.project.item(p).name===n)throw new Error("generated_name_collision:"+n);for(var i=1;i<=src.numLayers;i++)if(src.layer(i).source instanceof CompItem)preflight(src.layer(i).source,false);}preflight(source,true);var map={},names=[],cloneCount=0;
function clone(src){var key=__key(src);if(map[key])return map[key];var sourceId=__stableId(src),c=src.duplicate();c.name=desired[key];c.comment=__owner()+"|SOURCE:"+encodeURIComponent(src.name);c.motionBlur=false;c.shutterAngle=0;map[key]=c;cloneCount++;names.push({sourceItemIndex:__idx(src),sourceItemId:sourceId,originalName:src.name,cloneItemIndex:__idx(c),cloneItemId:__stableId(c),cloneName:c.name});for(var i=1;i<=c.numLayers;i++){var l=c.layer(i),old=l.source;l.locked=false;l.motionBlur=false;__zeroShutter(l);if(old instanceof CompItem)l.replaceSource(clone(old),false);if(l.hasAudio&&__d.audioMode==="mute")l.audioEnabled=false;}return c;}var sourceFingerprint=__fingerprintSummary(__structure(source)),root=clone(source);
return {ok:true,operation:"clone_tree",rootCompItemIndex:__idx(root),rootCompItemId:__stableId(root),rootCompName:root.name,audioMode:__d.audioMode,cloneNames:names,sourceFingerprint:sourceFingerprint,postVerification:{ok:root.name.indexOf(__d.generatedPrefix)===0,generatedComps:cloneCount,sourceDuration:source.duration}};`;
}

function extendScript(d) { return prelude(d)+String.raw`
var root=__generated(__item(__d.rootCompItemIndex,__d.expectedRootCompName)),moved=0,tiled=0;
function hasKeys(prop){if(prop.numProperties){for(var h=1;h<=prop.numProperties;h++)if(hasKeys(prop.property(h)))return true;return false;}return !!prop.numKeys;}
function preflightKeyValues(c,l,p,path){if(p.numProperties){for(var j=1;j<=p.numProperties;j++){var child=p.property(j),next=path.slice();next.push(__propertyPathEntry(child,j));preflightKeyValues(c,l,child,next);}return;}if(!p.numKeys)return;var identity=__propertyIdentity(c,l,path);for(var k=1;k<=p.numKeys;k++)__typedKeyValue(p,k,identity);}
__walk(root,function(c){for(var li=1;li<=c.numLayers;li++){var layer=c.layer(li);preflightKeyValues(c,layer,layer,[]);if(__d.targetDuration<=c.duration+Math.max(c.frameDuration*2,.07))continue;var isStill=layer.source instanceof FootageItem&&layer.source.mainSource&&layer.source.mainSource.isStill;if(layer.source instanceof FootageItem&&!isStill&&layer.enabled&&layer.outPoint>layer.inPoint&&layer.outPoint<__d.targetDuration-c.frameDuration/2&&hasKeys(layer))throw new Error("keyed_finite_footage_tiling_forbidden:"+c.name+"/"+layer.name);}});
function moveKeys(prop,oldDuration){
  if(prop.numProperties){for(var p=1;p<=prop.numProperties;p++)moveKeys(prop.property(p),oldDuration);return;}
  if(!prop.numKeys||!prop.canVaryOverTime||prop.propertyValueType===PropertyValueType.MARKER||prop.propertyValueType===PropertyValueType.CUSTOM_VALUE||prop.propertyValueType===PropertyValueType.NO_VALUE||(prop.canSetExpression&&prop.expression))return;
  var delta=__d.targetDuration-oldDuration,threshold=Math.max(__d.introDuration+.0001,oldDuration-2.1),rows=[],hasMoved=false;
  for(var k=1;k<=prop.numKeys;k++){var t=prop.keyTime(k),willMove=t>=threshold,nt=willMove?t+delta:t;if(willMove&&nt<=__d.introDuration)throw new Error("outro_key_crosses_intro:"+prop.name);var row={time:nt,value:prop.keyValue(k),inType:prop.keyInInterpolationType(k),outType:prop.keyOutInterpolationType(k),inEase:prop.keyInTemporalEase(k),outEase:prop.keyOutTemporalEase(k),temporalContinuous:prop.keyTemporalContinuous(k),temporalAutoBezier:prop.keyTemporalAutoBezier(k),moved:willMove};if(prop.isSpatial){row.inSpatial=prop.keyInSpatialTangent(k);row.outSpatial=prop.keyOutSpatialTangent(k);row.roving=prop.keyRoving(k);row.spatialContinuous=prop.keySpatialContinuous(k);row.spatialAutoBezier=prop.keySpatialAutoBezier(k);}rows.push(row);if(willMove)hasMoved=true;}
  if(!hasMoved)return;for(var collision=1;collision<rows.length;collision++)if(Math.abs(rows[collision].time-rows[collision-1].time)<.000001)throw new Error("translated_key_time_collision:"+prop.name+":"+rows[collision].time);
  for(var r=prop.numKeys;r>=1;r--)prop.removeKey(r);for(var add=0;add<rows.length;add++)prop.setValueAtTime(rows[add].time,rows[add].value);
  for(var q=0;q<rows.length;q++){var a=rows[q],ni=prop.nearestKeyIndex(a.time);prop.setTemporalEaseAtKey(ni,a.inEase,a.outEase);prop.setTemporalContinuousAtKey(ni,a.temporalContinuous);prop.setTemporalAutoBezierAtKey(ni,a.temporalAutoBezier);if(prop.isSpatial){prop.setSpatialTangentsAtKey(ni,a.inSpatial,a.outSpatial);prop.setRovingAtKey(ni,a.roving);prop.setSpatialContinuousAtKey(ni,a.spatialContinuous);prop.setSpatialAutoBezierAtKey(ni,a.spatialAutoBezier);}prop.setInterpolationTypeAtKey(ni,a.inType,a.outType);if(a.moved)moved++;}
}
__walk(root,function(c){
  var old=c.duration,extensionThreshold=Math.max(c.frameDuration*2,.07),growing=__d.targetDuration>old+extensionThreshold,frozen=[];for(var fi=1;fi<=c.numLayers;fi++){var original=c.layer(fi);frozen.push({layer:original,outPoint:original.outPoint,inPoint:original.inPoint,enabled:original.enabled});}
  c.motionBlur=false;c.shutterAngle=0;
  for(var i=0;i<frozen.length;i++){var pair=frozen[i],l=pair.layer;if(l.timeRemapEnabled)throw new Error("time_remap_forbidden:"+l.name);if(Math.abs(l.stretch-100)>.001)throw new Error("stretch_forbidden:"+l.name);l.motionBlur=false;__zeroShutter(l);if(growing)moveKeys(l,old);
    if(!growing){if(l.outPoint>__d.targetDuration)l.outPoint=__d.targetDuration;continue;}
    if(l.source instanceof CompItem||(l.source instanceof FootageItem&&l.source.mainSource&&l.source.mainSource.isStill)||!l.source){if(pair.outPoint>=old-Math.max(2.1,c.frameDuration*2)&&pair.inPoint<__d.targetDuration)l.outPoint=__d.targetDuration;continue;}
    if(l.source instanceof FootageItem&&pair.enabled&&pair.outPoint>pair.inPoint){var sourceIn=Math.max(0,pair.inPoint-l.startTime),available=Math.max(c.frameDuration,l.source.duration-sourceIn),cursor=pair.outPoint,repeats=0;if(sourceIn>=l.source.duration)throw new Error("sourceIn_exceeds_footage:"+l.name);while(cursor<__d.targetDuration-c.frameDuration/2){var dup=l.duplicate(),chunk=Math.min(available,__d.targetDuration-cursor);dup.startTime=cursor-sourceIn;dup.inPoint=cursor;dup.outPoint=cursor+chunk;dup.stretch=100;if(dup.timeRemapEnabled)dup.timeRemapEnabled=false;dup.motionBlur=false;__zeroShutter(dup);cursor+=chunk;tiled++;repeats++;if(repeats>=100)throw new Error("runaway_1x_tiling");}continue;}
    if(pair.outPoint>=old-Math.max(2.1,c.frameDuration*2)&&pair.inPoint<__d.targetDuration)l.outPoint=__d.targetDuration;
  }
  c.duration=__d.targetDuration;
});
return {ok:true,operation:"extend_tree",rootCompItemIndex:__idx(root),movedKeys:moved,tiledLayers:tiled,postVerification:{ok:Math.abs(root.duration-__d.targetDuration)<.001,targetDuration:root.duration}};`; }

function rewriteScript(d) { return prelude(d)+String.raw`
var root=__generated(__item(__d.rootCompItemIndex,__d.expectedRootCompName)),changed=0,derived=[],targets={},records=[],mappings=[],mappingBySource={};
function exactTarget(name){if(targets["$"+name])return;var count=0;for(var i=1;i<=app.project.numItems;i++){var item=app.project.item(i);if(item instanceof CompItem&&item.name===name)count++;}if(count!==1)throw new Error("expression_target_identity_mismatch:"+name);targets["$"+name]=true;}
function addMapping(kind,from,to,required){if(from===to)throw new Error("expression_replacement_noop:"+from);var key="$"+from,prior=mappingBySource[key];if(prior){if(prior.to!==to)throw new Error("expression_source_ambiguous:"+from);if(required){prior.required=true;prior.kind="requested";}return prior;}var row={kind:kind,from:from,to:to,required:required===true,occurrencesBefore:0,occurrencesAfter:0,destinationOccurrencesBefore:0,destinationOccurrencesAfter:0,changedProperties:[]};mappingBySource[key]=row;mappings.push(row);return row;}
function countRef(value,name){var doubleRef="comp("+__exprDouble(name)+")",singleRef="comp("+__exprSingle(name)+")";return String(value).split(doubleRef).length-1+String(value).split(singleRef).length-1;}
function replaceRef(value,from,to){var replacement="comp("+__exprDouble(to)+")";return String(value).split("comp("+__exprDouble(from)+")").join(replacement).split("comp("+__exprSingle(from)+")").join(replacement);}
exactTarget(__d.masterCompName);addMapping("master","Final Comp",__d.masterCompName,false);for(var et=0;et<__d.replacements.length;et++){exactTarget(__d.replacements[et].to);addMapping("requested",__d.replacements[et].from,__d.replacements[et].to,true);}
__walk(root,function(c){var marker="|SOURCE:",at=String(c.comment||"").indexOf(marker);if(at<0)throw new Error("clone_provenance_missing:"+c.name);derived.push({from:decodeURIComponent(String(c.comment).substring(at+marker.length)),to:c.name});});
for(var di=0;di<derived.length;di++){exactTarget(derived[di].to);addMapping("derived",derived[di].from,derived[di].to,false);}
for(var mi=0;mi<mappings.length;mi++)for(var mj=0;mj<mappings.length;mj++)if(mi!==mj&&mappings[mi].to===mappings[mj].from)throw new Error("expression_replacement_chain_unsupported:"+mappings[mi].from+":"+mappings[mj].from);
__walk(root,function(c){for(var i=1;i<=c.numLayers;i++){var l=c.layer(i);function scan(p,path){if(p.numProperties){for(var j=1;j<=p.numProperties;j++){var child=p.property(j),next=path.slice();next.push(__propertyPathEntry(child,j));scan(child,next);}return;}if(!p.canSetExpression||!p.expression)return;records.push({property:p,comp:c,layer:l,propertyPath:path,propertyIdentity:__propertyIdentity(c,l,path),before:String(p.expression),after:null});}scan(l,[]);}});
for(var grammar=0;grammar<records.length;grammar++){var calls=records[grammar].before.match(/\bcomp\s*\([^)]*\)/g)||[];for(var call=0;call<calls.length;call++)if(!/^comp\((?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')\)$/.test(calls[call]))throw new Error("unsupported_expression_comp_reference:"+records[grammar].propertyIdentity);}
for(var mb=0;mb<mappings.length;mb++){var mapping=mappings[mb];for(var rb=0;rb<records.length;rb++){mapping.occurrencesBefore+=countRef(records[rb].before,mapping.from);mapping.destinationOccurrencesBefore+=countRef(records[rb].before,mapping.to);}if(mapping.required&&mapping.occurrencesBefore===0)throw new Error("requested_expression_source_missing:"+mapping.from);}
for(var ri=0;ri<records.length;ri++){var record=records[ri],after=record.before;for(var ma=0;ma<mappings.length;ma++)after=replaceRef(after,mappings[ma].from,mappings[ma].to);record.after=after;if(after!==record.before){record.property.expression=after;var readBack=String(record.property.expression);if(record.property.expressionError)throw new Error("expression_rewrite_failed:"+record.property.expressionError);if(readBack!==after)throw new Error("expression_readback_mismatch:"+record.propertyIdentity);record.after=readBack;changed++;}}
var replacementsProven=true;for(var mp=0;mp<mappings.length;mp++){var proof=mappings[mp];for(var rp=0;rp<records.length;rp++){var sourceBefore=countRef(records[rp].before,proof.from),sourceAfter=countRef(records[rp].after,proof.from),destinationBefore=countRef(records[rp].before,proof.to),destinationAfter=countRef(records[rp].after,proof.to);proof.occurrencesAfter+=sourceAfter;proof.destinationOccurrencesAfter+=destinationAfter;if(sourceBefore>0)proof.changedProperties.push({propertyIdentity:records[rp].propertyIdentity,compItemId:__stableId(records[rp].comp),layerId:__stableId(records[rp].layer),propertyPath:records[rp].propertyPath,before:records[rp].before,after:records[rp].after,sourceOccurrencesBefore:sourceBefore,sourceOccurrencesAfter:sourceAfter,destinationOccurrencesBefore:destinationBefore,destinationOccurrencesAfter:destinationAfter});}proof.status=proof.occurrencesBefore>0?"replaced":"not_referenced";if(proof.occurrencesBefore>0&&(proof.occurrencesAfter!==0||proof.destinationOccurrencesAfter<proof.destinationOccurrencesBefore+proof.occurrencesBefore))replacementsProven=false;if(proof.required&&proof.occurrencesBefore===0)replacementsProven=false;delete proof.required;}
if(!replacementsProven)throw new Error("expression_replacement_readback_failed");
return {ok:true,operation:"rewrite_expressions",changed:changed,rootCompItemIndex:__idx(root),expressionReplacements:mappings,postVerification:{ok:true,expressionCount:changed,replacementsProven:replacementsProven}};`; }

function textScript(d) { return prelude(d)+String.raw`
var root=__generated(__item(__d.rootCompItemIndex,__d.expectedRootCompName)),titleComp=null,titleLayer=null,changed=0,roles={title:0,label:0,heading:0,body:0},article=__d.articleChunks.join("\r\r"),cursor=0;function wrap(s,n){var words=s.replace(/\r?\n/g," ").replace(/\s+/g," ").split(" "),lines=[],line="";for(var i=0;i<words.length;i++){var next=line?line+" "+words[i]:words[i];if(line&&next.length>n){lines.push(line);line=words[i];}else line=next;}if(line)lines.push(line);return lines.join("\r");}function nextChunk(amount){amount=Math.max(amount,80);if(cursor>=article.length-80)cursor=0;var end=article.length-cursor<=amount*1.25?article.length:Math.min(article.length,cursor+amount);if(end<article.length){var p=end;while(p>cursor+Math.floor(amount*.7)&&!(/\s/.test(article.charAt(p))))p--;if(p>cursor)end=p;}var out=article.substring(cursor,end).replace(/^\s+|\s+$/g,"");cursor=end;if(out.length<40){cursor=0;out=article.substring(0,Math.min(amount,article.length)).replace(/^\s+|\s+$/g,"");cursor=out.length;}return out;}function hero(){if(__d.hero==="suhanov")return "ПЁТР СУХАНОВ";if(__d.hero==="kurnikov")return "АНАТОЛИЙ КУРНИКОВ";return "ПЁТР СУХАНОВ • АНАТОЛИЙ КУРНИКОВ";}function fitWidth(c,l,p,doc,max){var n=0,r=l.sourceRectAtTime(0,false);while(n<40&&doc.fontSize>10&&r.width>c.width*max){doc.fontSize-=1;p.setValue(doc);r=l.sourceRectAtTime(0,false);n++;}}
__walk(root,function(c){var isTitle=c.name===__d.expectedTitleCompName||c.name.slice(-(__d.expectedTitleCompName.length+2))==="__"+__d.expectedTitleCompName;if(isTitle)titleComp=c;for(var i=1;i<=c.numLayers;i++){var l=c.layer(i),g=l.property("ADBE Text Properties"),p=g&&g.property("ADBE Text Document");if(!p||p.expressionEnabled)continue;var old=String(p.value.text||""),doc=p.value;if(isTitle&&!titleLayer){titleLayer=l;__clear(p);doc=p.value;doc.text=wrap(__d.title,__d.titleWrap);doc.font="TimesNewRomanPS-BoldMT";doc.fontSize=Math.min(64,Math.max(28,c.height*.28));doc.autoLeading=true;doc.justification=ParagraphJustification.CENTER_JUSTIFY;doc.applyFill=true;p.setValue(doc);var tr=l.property("ADBE Transform Group"),sc=tr.property("ADBE Scale"),an=tr.property("ADBE Anchor Point"),pos=tr.property("ADBE Position");__clear(sc);__clear(an);__clear(pos);sc.setValue(sc.value.length===3?[100,100,100]:[100,100]);var rect=l.sourceRectAtTime(0,false),tries=0;while(tries<80&&doc.fontSize>16&&(rect.width>c.width*.90||rect.height>c.height*.86)){doc.fontSize-=1;p.setValue(doc);rect=l.sourceRectAtTime(0,false);tries++;}an.setValue(an.value.length===3?[rect.left+rect.width/2,rect.top+rect.height/2,an.value[2]]:[rect.left+rect.width/2,rect.top+rect.height/2]);pos.setValue(pos.value.length===3?[c.width/2,c.height/2,pos.value[2]]:[c.width/2,c.height/2]);roles.title++;changed++;continue;}var role,value;if(old.length>=220){role="body";value=nextChunk(Math.ceil(old.length*1.05));}else if(old.length<45){role="label";value=hero();}else{role="heading";value=nextChunk(Math.max(old.length,100));}doc.text=value;doc.font="TimesNewRomanPSMT";p.setValue(doc);if(role!=="body")fitWidth(c,l,p,doc,.92);roles[role]++;changed++;}});
if(!titleComp||!titleLayer)throw new Error("title_comp_or_layer_not_found");var baked="Scene "+__d.sceneNumber+" Text";for(var r=1;r<=root.numLayers;r++){var layer=root.layer(r);if(layer.source instanceof CompItem&&(layer.source.name===baked||layer.source.name.slice(-(baked.length+2))==="__"+baked)){layer.enabled=false;if(layer.hasAudio)layer.audioEnabled=false;}if(layer.property("ADBE Text Properties")||layer instanceof ShapeLayer){var op=layer.property("ADBE Transform Group").property("ADBE Opacity");if(op&&Number(op.value)===0){__clear(op);op.setValue(100);layer.enabled=true;}}}return {ok:true,operation:"event_text",changed:changed,roles:roles,postVerification:{ok:roles.title===1,titleCompName:titleComp.name}};`; }

function mediaScript(d) { return prelude(d)+`
var root=__generated(__item(__d.rootCompItemIndex,__d.expectedRootCompName)),parents=[],template=null,sources=[];for(var z=1;z<=app.project.numItems;z++)if(app.project.item(z).name===__d.generatedLeafName)throw new Error("generated_name_collision:"+__d.generatedLeafName);__walk(root,function(c){for(var i=1;i<=c.numLayers;i++){var l=c.layer(i);if(l.source instanceof CompItem&&(l.source.name===__d.leafName||l.source.name.slice(-(__d.leafName.length+2))==="__"+__d.leafName)){parents.push(l);template=l.source;}}});if(!parents.length||!template)throw new Error("media_leaf_not_found:"+__d.leafName);for(var si=0;si<__d.mediaItems.length;si++){var checked=__footage(__d.mediaItems[si].path),isStill=checked.mainSource&&checked.mainSource.isStill;if(!isStill&&__d.mediaItems[si].sourceIn>=checked.duration)throw new Error("sourceIn_exceeds_media:"+checked.name);if(__d.mediaItems[si].audio===true&&!checked.hasAudio)throw new Error("audio_requested_for_silent_media:"+checked.name);sources.push(checked);}var leaf=app.project.items.addComp(__d.generatedLeafName,template.width,template.height,template.pixelAspect,__d.duration,template.frameRate);leaf.comment=__owner();var made=0;for(var m=0;m<__d.mediaItems.length;m++){var spec=__d.mediaItems[m],src=sources[m],still=src.mainSource&&src.mainSource.isStill;var available=still?spec.duration:Math.max(leaf.frameDuration,src.duration-spec.sourceIn),used=0,part=0;while(used<spec.duration-.000001){var remaining=spec.duration-used,chunk=still?remaining:Math.min(available,remaining);if(!isFinite(chunk)||chunk<=.000001)throw new Error("invalid_media_chunk:"+m+":"+part);var layer=leaf.layers.add(src);layer.name=__d.generatedPrefix+"MEDIA_"+(m+1)+(part?"_PART_"+(part+1):"");layer.startTime=spec.start+used-spec.sourceIn;layer.inPoint=spec.start+used;layer.outPoint=spec.start+used+chunk;layer.stretch=100;if(layer.timeRemapEnabled)layer.timeRemapEnabled=false;layer.motionBlur=false;if(layer.hasAudio)layer.audioEnabled=spec.audio===true;layer.enabled=true;var tr=layer.property("ADBE Transform Group"),sc=tr.property("ADBE Scale"),pos=tr.property("ADBE Position");if(!sc||!pos)throw new Error("media_transform_unavailable");var cover=Math.max(leaf.width/src.width,leaf.height/src.height)*100;sc.setValue(sc.value.length===3?[cover,cover,cover]:[cover,cover]);pos.setValue(pos.value.length===3?[leaf.width/2,leaf.height/2,pos.value[2]]:[leaf.width/2,leaf.height/2]);used+=chunk;part++;made++;if(still)break;if(part>=100)throw new Error("runaway_media_tiling");}}
for(var p=0;p<parents.length;p++)parents[p].replaceSource(leaf,false);return {ok:true,operation:"replace_media_leaf",leafCompItemIndex:__idx(leaf),leafCompName:leaf.name,relinkedLayers:parents.length,mediaLayers:made,postVerification:{ok:leaf.name.indexOf(__d.generatedPrefix)===0&&leaf.numLayers===made}};`; }

function pairScript(d) { return prelude(d)+String.raw`
var finalComp=__item(__d.finalCompItemIndex,__d.expectedFinalCompName),master=__generated(__item(__d.masterCompItemIndex,__d.expectedMasterCompName)),root=__generatedAs(__item(__d.rootCompItemIndex,__d.expectedRootCompName),__d.expectedRootCompName),introName=__d.generatedPrefix+"EVENT_"+__d.eventToken+"_INTRO",mainName=__d.generatedPrefix+"EVENT_"+__d.eventToken+"_MAIN";
for(var ci=1;ci<=master.numLayers;ci++)if(master.layer(ci).name===introName||master.layer(ci).name===mainName)throw new Error("generated_event_collision:"+master.layer(ci).name);
var found=[];for(var i=1;i<=finalComp.numLayers;i++){var l=finalComp.layer(i);if(l.name===__d.sourceSceneName&&l.source instanceof CompItem&&l.source.name===__d.sourceSceneName)found.push(l);}var intro,main;
if(__d.sceneNumber===1){if(found.length!==1)throw new Error("scene1_single_source_required");intro=found[0];main=found[0];}else{if(found.length!==2)throw new Error("scene_pair_exactly_two_required");var ad=found[0].outPoint-found[0].inPoint,bd=found[1].outPoint-found[1].inPoint;intro=ad<=bd?found[0]:found[1];main=intro===found[0]?found[1]:found[0];if(Math.abs((intro.outPoint-intro.inPoint)-__d.introDuration)>.051)throw new Error("scene_intro_duration_mismatch");if(Math.abs(intro.outPoint-main.inPoint)>.051)throw new Error("scene_pair_not_adjacent");}
function effectCount(layer){var fx=layer.property("ADBE Effect Parade");return fx?fx.numProperties:0;}var introSourceEffects=effectCount(intro),mainSourceEffects=effectCount(main);if(introSourceEffects!==__d.introEffectCount)throw new Error("scene_intro_effect_count_mismatch:"+introSourceEffects+":"+__d.introEffectCount);if(mainSourceEffects!==__d.mainEffectCount)throw new Error("scene_main_effect_count_mismatch:"+mainSourceEffects+":"+__d.mainEffectCount);
var specs=[{src:main,name:mainName,inPoint:__d.eventStart+__d.introDuration,outPoint:__d.eventStart+__d.eventDuration},{src:intro,name:introName,inPoint:__d.eventStart,outPoint:__d.eventStart+__d.introDuration}],made=[];
for(var sid=0;sid<specs.length;sid++)if(!specs[sid].src||typeof specs[sid].src.id!=="number")throw new Error("stable_source_layer_id_unavailable:"+sid);for(var tid=1;tid<=master.numLayers;tid++)if(!master.layer(tid)||typeof master.layer(tid).id!=="number")throw new Error("stable_target_layer_id_unavailable:"+tid);
for(var j=0;j<specs.length;j++){var spec=specs[j],copy=__copyLayerToComp(spec.src,master);copy.locked=false;copy.replaceSource(root,false);copy.name=spec.name;copy.startTime=__d.eventStart;copy.inPoint=spec.inPoint;copy.outPoint=spec.outPoint;copy.stretch=100;if(copy.timeRemapEnabled)copy.timeRemapEnabled=false;copy.motionBlur=false;__zeroShutter(copy);copy.enabled=true;if(copy.hasAudio)copy.audioEnabled=__d.rootHasAudio===true;var copiedEffects=effectCount(copy),expectedEffects=spec.src===intro?__d.introEffectCount:__d.mainEffectCount;if(copiedEffects!==expectedEffects)throw new Error("copied_effect_count_mismatch:"+copiedEffects+":"+expectedEffects);made.push({index:copy.index,layerId:copy.id,name:copy.name,inPoint:copy.inPoint,outPoint:copy.outPoint,startTime:copy.startTime,audioEnabled:copy.hasAudio?copy.audioEnabled:false,effects:copiedEffects});}
for(var refresh=0;refresh<made.length;refresh++){var current=null,currentCount=0;for(var currentIndex=1;currentIndex<=master.numLayers;currentIndex++){var currentLayer=master.layer(currentIndex);if(currentLayer.id===made[refresh].layerId){current=currentLayer;currentCount++;}}if(currentCount!==1)throw new Error("copied_layer_refresh_mismatch:"+made[refresh].layerId+":"+currentCount);made[refresh].index=current.index;}
return {ok:true,operation:"copy_event_pair",layers:made,masterCompItemIndex:__idx(master),postVerification:{ok:made.length===2,eventStart:__d.eventStart,eventEnd:__d.eventStart+__d.eventDuration}};`; }

function overlayScript(d) { return prelude(d)+String.raw`
var master=__generated(__item(__d.masterCompItemIndex,__d.expectedMasterCompName)),audioPrefix=__d.generatedPrefix+"AUDIO_"+__d.eventId+"_",captionPrefix=__d.generatedPrefix+"CAPTION_"+__d.eventId+"_";
for(var ci=1;ci<=master.numLayers;ci++){var existing=master.layer(ci).name;if(existing.indexOf(audioPrefix)===0||existing.indexOf(captionPrefix)===0)throw new Error("generated_overlay_collision:"+existing);}
var sources=[];for(var si=0;si<__d.audioItems.length;si++){var audioSpec=__d.audioItems[si],audioSource=__footage(audioSpec.path);if(!audioSource.hasAudio)throw new Error("audioOnly_source_has_no_audio:"+audioSource.name);if(audioSpec.sourceIn>=audioSource.duration)throw new Error("sourceIn_exceeds_audio:"+audioSource.name);sources.push(audioSource);}
var audio=0,captions=0;for(var i=0;i<__d.audioItems.length;i++){var spec=__d.audioItems[i],src=sources[i],available=Math.max(master.frameDuration,src.duration-spec.sourceIn),used=0,part=0;while(used<spec.duration-.000001){var remaining=spec.duration-used,chunk=Math.min(available,remaining);if(!isFinite(chunk)||chunk<=.000001)throw new Error("invalid_audio_chunk:"+i+":"+part);var l=master.layers.add(src),absolute=__d.eventStart+spec.start+used;l.name=audioPrefix+(i+1)+(part?"_PART_"+(part+1):"");l.startTime=absolute-spec.sourceIn;l.inPoint=absolute;l.outPoint=absolute+chunk;l.enabled=false;l.audioEnabled=true;l.stretch=100;if(l.timeRemapEnabled)l.timeRemapEnabled=false;l.motionBlur=false;audio++;used+=chunk;part++;if(part>=100)throw new Error("runaway_audio_tiling");}}
for(var c=0;c<__d.captions.length;c++){var t=master.layers.addText(__d.captions[c]);t.name=captionPrefix+(c+1);t.startTime=__d.eventStart;t.inPoint=__d.eventStart;t.outPoint=__d.eventStart+__d.eventDuration;t.motionBlur=false;var p=t.property("ADBE Text Properties").property("ADBE Text Document"),doc=p.value;doc.font="TimesNewRomanPSMT";doc.fontSize=32;doc.applyFill=true;doc.fillColor=[.12,.10,.08];p.setValue(doc);var rect=t.sourceRectAtTime(__d.eventStart,false),tr=t.property("ADBE Transform Group"),an=tr.property("ADBE Anchor Point"),pos=tr.property("ADBE Position");an.setValue([rect.left+rect.width/2,rect.top+rect.height/2]);pos.setValue([c%2===0?master.width*.25:master.width*.75,master.height*.90]);captions++;}
return {ok:true,operation:"event_overlays",audioLayers:audio,captionLayers:captions,postVerification:{ok:captions===__d.captions.length}};`; }

function controlScript(d) { return prelude(d)+String.raw`
var source=__item(__d.sourceCompItemIndex,__d.expectedSourceCompName),master=__generated(__item(__d.masterCompItemIndex,__d.expectedMasterCompName)),found=[];for(var mi=1;mi<=master.numLayers;mi++)if(master.layer(mi).name===__d.targetLayerName)throw new Error("generated_control_collision:"+__d.targetLayerName);for(var i=1;i<=source.numLayers;i++)if(source.layer(i).name===__d.sourceLayerName)found.push(source.layer(i));if(found.length!==1)throw new Error("control_layer_identity_mismatch:"+__d.sourceLayerName+":"+found.length);var sourceFx=found[0].property("ADBE Effect Parade"),sourceEffects=sourceFx?sourceFx.numProperties:0;if(sourceEffects!==__d.expectedEffectCount)throw new Error("control_effect_count_mismatch:"+sourceEffects+":"+__d.expectedEffectCount);var l=__copyLayerToComp(found[0],master);l.locked=false;l.name=__d.targetLayerName;l.comment=__owner()+":"+__d.targetLayerName;l.startTime=0;l.inPoint=0;l.outPoint=__d.duration;l.motionBlur=false;__zeroShutter(l);l.enabled=false;if(l.hasAudio)l.audioEnabled=false;if(l instanceof AVLayer){l.stretch=100;if(l.timeRemapEnabled)l.timeRemapEnabled=false;}var copiedFx=l.property("ADBE Effect Parade"),copiedEffects=copiedFx?copiedFx.numProperties:0;if(copiedEffects!==__d.expectedEffectCount)throw new Error("copied_control_effect_count_mismatch:"+copiedEffects+":"+__d.expectedEffectCount);return {ok:true,operation:"copy_control_layer",sourceCompItemId:__stableId(source),targetLayerName:__d.targetLayerName,layer:{index:l.index,layerId:l.id,name:l.name,comment:l.comment,effects:copiedEffects},postVerification:{ok:l.name===__d.targetLayerName&&l.outPoint===__d.duration&&copiedEffects===__d.expectedEffectCount}};`; }

function auditScript(d) { return prelude(d)+String.raw`
var root=__generated(__item(__d.rootCompItemIndex,__d.expectedRootCompName)),issues=[],stats={comps:0,layers:0,keyframes:0,keyMetadataTotal:0,spatialKeys:0,audibleLayers:0,videoLayers:0,effects:0,captions:0,eventLayers:0,backgroundLayers:0},details={texts:[],layers:[],expressions:[],expressionProvenance:[],keyMetadata:[],keyMetadataTruncated:false,externalDependencies:[]};
function plainEases(values){var result=[];for(var ei=0;ei<values.length;ei++)result.push({speed:Number(values[ei].speed),influence:Number(values[ei].influence)});return result;}
if(Math.abs(root.duration-__d.expectedDuration)>.051)issues.push(root.name+":duration");
__walkRead(root,function(c){
  stats.comps++;if(c.motionBlur)issues.push(c.name+":comp_motion_blur");var provenanceMarker="|SOURCE:",provenanceAt=String(c.comment||"").indexOf(provenanceMarker);if(provenanceAt>=0){try{var provenanceSource=decodeURIComponent(String(c.comment).substring(provenanceAt+provenanceMarker.length));if(!provenanceSource)issues.push(c.name+":clone_provenance_malformed");else details.expressionProvenance.push({comp:c.name,compItemId:__stableId(c),sourceName:provenanceSource});}catch(provenanceError){issues.push(c.name+":clone_provenance_malformed");}}var audibleSources={};
  for(var i=1;i<=c.numLayers;i++){
    var l=c.layer(i),sourcePath="";stats.layers++;if(l.enabled)stats.videoLayers++;if(l.hasAudio&&l.audioEnabled)stats.audibleLayers++;if(l.name===__d.generatedPrefix+"BACKGROUND")stats.backgroundLayers++;if(l.name.indexOf(__d.generatedPrefix+"CAPTION_")===0)stats.captions++;if(l.name.indexOf(__d.generatedPrefix+"EVENT_")===0)stats.eventLayers++;
    if(l.source instanceof FootageItem&&l.source.file)sourcePath=l.source.file.fsName;
    var fx=l.property("ADBE Effect Parade"),effectCount=fx?fx.numProperties:0;stats.effects+=effectCount;
    var sourceType=l.source instanceof CompItem?"comp":(l.source instanceof FootageItem?"footage":"none"),sourceFrameDuration=l.source&&typeof l.source.frameDuration==="number"&&isFinite(l.source.frameDuration)?Number(l.source.frameDuration):null;
    details.layers.push({comp:c.name,compItemId:__stableId(c),compFrameDuration:Number(c.frameDuration),name:l.name,layer:l.name,layerId:__stableId(l),sourceType:sourceType,sourceName:l.source?l.source.name:null,sourceItemIndex:l.source?__idx(l.source):null,sourceItemId:l.source?__stableId(l.source):null,sourcePath:sourcePath,sourceFrameDuration:sourceFrameDuration,sourceSampleRate:null,hasVideo:typeof l.hasVideo==="boolean"?!!l.hasVideo:(l.source&&typeof l.source.hasVideo==="boolean"?!!l.source.hasVideo:!!l.source),hasAudio:!!l.hasAudio,enabled:!!l.enabled,audioEnabled:l.hasAudio?!!l.audioEnabled:false,startTime:Number(l.startTime),inPoint:Number(l.inPoint),outPoint:Number(l.outPoint),sourceIn:Number(l.inPoint-l.startTime),stretch:l instanceof AVLayer?Number(l.stretch):null,effects:effectCount,comment:l.comment||""});
    if(l.hasAudio&&l.audioEnabled&&l.source instanceof CompItem){var ak=String(__stableId(l.source)),ranges=audibleSources[ak]||[],offset=Number(l.startTime);for(var ar=0;ar<ranges.length;ar++)if(Math.abs(ranges[ar].offset-offset)<.000001&&Math.max(ranges[ar].start,l.inPoint)<Math.min(ranges[ar].end,l.outPoint)-.001)issues.push(c.name+":duplicate_audible_path:"+l.source.name);ranges.push({start:l.inPoint,end:l.outPoint,offset:offset});audibleSources[ak]=ranges;}
    if(l.motionBlur)issues.push(c.name+"/"+l.name+":motion_blur");if(l instanceof AVLayer){if(l.timeRemapEnabled)issues.push(c.name+"/"+l.name+":time_remap");if(Math.abs(l.stretch-100)>.001)issues.push(c.name+"/"+l.name+":stretch");}
    var tg=l.property("ADBE Text Properties"),tp=tg&&tg.property("ADBE Text Document");if(tp){var td=tp.value,tr=l.property("ADBE Transform Group"),rect=l.sourceRectAtTime(c.time||0,false);details.texts.push({comp:c.name,compWidth:c.width,compHeight:c.height,layer:l.name,text:String(td.text),font:String(td.font),fontSize:Number(td.fontSize),rect:{left:rect.left,top:rect.top,width:rect.width,height:rect.height},anchor:tr.property("ADBE Anchor Point").value,position:tr.property("ADBE Position").value});}
    if(fx)for(var efx=1;efx<=fx.numProperties;efx++){var ef=fx.property(efx);if(ef.matchName==="ADBE Geometry2"){var sh=ef.property("ADBE Geometry2-0010");if(sh&&Number(sh.value)!==0)issues.push(c.name+"/"+l.name+":transform_shutter");}}
    function scan(p,path){if(p.numProperties){for(var j=1;j<=p.numProperties;j++){var child=p.property(j),next=path.slice();next.push(__propertyPathEntry(child,j));scan(child,next);}return;}var identity=__propertyIdentity(c,l,path);if(p.numKeys){stats.keyframes+=p.numKeys;if(p.isSpatial)stats.spatialKeys+=p.numKeys;stats.keyMetadataTotal+=p.numKeys;for(var k=1;k<=p.numKeys;k++){var typedValue=__typedKeyValue(p,k,identity);if(details.keyMetadata.length<20000)details.keyMetadata.push({comp:c.name,compItemId:__stableId(c),compDuration:Number(c.duration),compFrameDuration:Number(c.frameDuration),translationEligible:!!p.canVaryOverTime&&!(p.canSetExpression&&p.expression),layer:l.name,layerId:__stableId(l),property:p.matchName||p.name,propertyIdentity:identity,propertyPath:path,keyIndex:k,time:Number(p.keyTime(k)),value:typedValue,inType:String(p.keyInInterpolationType(k)),outType:String(p.keyOutInterpolationType(k)),inEase:plainEases(p.keyInTemporalEase(k)),outEase:plainEases(p.keyOutTemporalEase(k)),temporalContinuous:p.keyTemporalContinuous(k),temporalAutoBezier:p.keyTemporalAutoBezier(k),spatial:!!p.isSpatial,inSpatial:p.isSpatial?p.keyInSpatialTangent(k):null,outSpatial:p.isSpatial?p.keyOutSpatialTangent(k):null,roving:p.isSpatial?p.keyRoving(k):null,spatialContinuous:p.isSpatial?p.keySpatialContinuous(k):null,spatialAutoBezier:p.isSpatial?p.keySpatialAutoBezier(k):null});}}if(p.canSetExpression&&p.expression){details.expressions.push({comp:c.name,compItemId:__stableId(c),layer:l.name,layerId:__stableId(l),property:p.matchName||p.name,propertyIdentity:identity,propertyPath:path,enabled:!!p.expressionEnabled,expression:String(p.expression),error:String(p.expressionError||"")});if(p.expressionEnabled&&p.expressionError)issues.push(c.name+"/"+l.name+"/"+p.name+":expression:"+p.expressionError);}}
    scan(l,[]);
  }
},details.externalDependencies);
details.keyMetadataTruncated=stats.keyMetadataTotal>details.keyMetadata.length;var fingerprints=[];for(var f=0;f<__d.sourceFingerprints.length;f++){var comparison=__compareFingerprint(__d.sourceFingerprints[f]);fingerprints.push(comparison);if(!comparison.unchanged)issues.push("source_fingerprint_changed:"+__d.sourceFingerprints[f].name+":"+comparison.reason);}
return {ok:issues.length===0,operation:"audit_generated",root:{itemIndex:__idx(root),itemId:__stableId(root),name:root.name,duration:Number(root.duration),frameDuration:Number(root.frameDuration)},stats:stats,details:details,sourceFingerprints:fingerprints,issues:issues};`; }

function audioScript(d) { return prelude(d)+`
var root=__generated(__item(__d.rootCompItemIndex,__d.expectedRootCompName)),comps=[],byId={},states={},routes=[],mutations=[],epsilon=.000001;
__walk(root,function(c){comps.push(c);byId[String(__stableId(c))]=c;});for(var pre=0;pre<comps.length;pre++){var checkedComp=comps[pre];for(var i=1;i<=checkedComp.numLayers;i++){var l=checkedComp.layer(i);__stableId(l);if(l.audioEnabled&&l.hasAudio&&(l.timeRemapEnabled||Math.abs(Number(l.stretch)-100)>.001))throw new Error("unsupported_audio_time_mapping:"+checkedComp.name+"/"+l.name);if(l.source instanceof CompItem&&!byId[String(__stableId(l.source))]&&l.audioEnabled&&l.hasAudio)throw new Error("external_audio_route_unsupported:"+checkedComp.name+"/"+l.name);}}
function overlap(a,b){return Math.max(a.start,b.start)<Math.min(a.end,b.end)-epsilon;}
function sameMapping(a,b){return a.sourceItemId===b.sourceItemId&&Math.abs(a.offset-b.offset)<=epsilon;}
function fullyCovered(path,coverage){var spans=[];for(var i=0;i<coverage.length;i++)if(sameMapping(path,coverage[i])&&overlap(path,coverage[i]))spans.push({start:Math.max(path.start,coverage[i].start),end:Math.min(path.end,coverage[i].end)});spans.sort(function(a,b){return a.start-b.start||b.end-a.end;});var cursor=path.start;for(var s=0;s<spans.length;s++){if(spans[s].start>cursor+epsilon)return false;if(spans[s].end>cursor)cursor=spans[s].end;if(cursor>=path.end-epsilon)return true;}return cursor>=path.end-epsilon;}
function mapChildPaths(layer,childPaths){var result=[];for(var i=0;i<childPaths.length;i++){var child=childPaths[i],start=Math.max(Number(layer.inPoint),child.start+Number(layer.startTime)),end=Math.min(Number(layer.outPoint),child.end+Number(layer.startTime));if(end>start+epsilon)result.push({sourceItemId:child.sourceItemId,start:start,end:end,offset:child.offset+Number(layer.startTime)});}return result;}
var ordered=[],visiting={},visited={};function order(c){var id=String(__stableId(c));if(visiting[id])throw new Error("cyclic_audio_dependency:"+c.name);if(visited[id])return;visiting[id]=true;for(var oi=1;oi<=c.numLayers;oi++){var nested=c.layer(oi).source;if(nested instanceof CompItem&&byId[String(__stableId(nested))])order(nested);}visiting[id]=false;visited[id]=true;ordered.push(c);}order(root);
for(var ci=0;ci<ordered.length;ci++){var comp=ordered[ci],coverage=[],candidates=[];for(var li=1;li<=comp.numLayers;li++){var layer=comp.layer(li),source=layer.source;if(source instanceof CompItem){var childState=states[String(__stableId(source))],paths=childState?mapChildPaths(layer,childState.paths):[];candidates.push({layer:layer,paths:paths,duration:Number(layer.outPoint)-Number(layer.inPoint)});continue;}if(layer.hasAudio&&layer.audioEnabled&&source){coverage.push({sourceItemId:__stableId(source),start:Number(layer.inPoint),end:Number(layer.outPoint),offset:Number(layer.startTime)});}}
  candidates.sort(function(a,b){return b.duration-a.duration||a.layer.index-b.layer.index;});
  for(var ca=0;ca<candidates.length;ca++){var candidate=candidates[ca],current=candidate.layer,before=!!current.audioEnabled,action="preserve_audible",reason="unique_audible_route",after=before,anyOverlap=false,allCovered=candidate.paths.length>0;for(var pi=0;pi<candidate.paths.length;pi++){var path=candidate.paths[pi],covered=fullyCovered(path,coverage);if(!covered)allCovered=false;for(var co=0;co<coverage.length;co++)if(sameMapping(path,coverage[co])&&overlap(path,coverage[co])){anyOverlap=true;break;}}
    if(!before){action="preserve_muted";reason="muted_before";after=false;}else if(!candidate.paths.length){action="preserve_no_audible_source";reason="source_has_no_audible_path";after=true;}else if(allCovered){action="mute_duplicate";reason="fully_covered_duplicate";after=false;mutations.push(current);}else if(anyOverlap){throw new Error("ambiguous_audible_overlap:"+comp.name+"/"+current.name);}else{for(var add=0;add<candidate.paths.length;add++)coverage.push(candidate.paths[add]);}
    var audiblePaths=[];for(var ap=0;ap<candidate.paths.length;ap++)audiblePaths.push({sourceItemId:candidate.paths[ap].sourceItemId,inPoint:candidate.paths[ap].start,outPoint:candidate.paths[ap].end,sourceIn:candidate.paths[ap].start-candidate.paths[ap].offset});routes.push({comp:comp.name,compItemId:__stableId(comp),layer:current.name,layerId:__stableId(current),sourceName:current.source.name,sourceItemId:__stableId(current.source),inPoint:Number(current.inPoint),outPoint:Number(current.outPoint),sourceIn:Number(current.inPoint-current.startTime),audiblePaths:audiblePaths,audioEnabledBefore:before,audioEnabledAfter:after,action:action,reason:reason});
  }
  states[String(__stableId(comp))]={paths:coverage};
}
for(var mu=0;mu<mutations.length;mu++)mutations[mu].audioEnabled=false;
routes.sort(function(a,b){return a.compItemId-b.compItemId||a.layerId-b.layerId;});var rootState=states[String(__stableId(root))],rootHasAudio=!!(rootState&&rootState.paths.length);return {ok:true,operation:"configure_tree_audio",rootHasAudio:rootHasAudio,mutedDuplicatePaths:mutations.length,audioRouteCountBefore:routes.length,audioRoutes:routes,postVerification:{ok:true,audioRouteCountBefore:routes.length,mutedDuplicatePaths:mutations.length}};`; }

function masterScript(d) { return prelude(d)+`
for(var i=1;i<=app.project.numItems;i++)if(app.project.item(i).name===__d.masterName)throw new Error("generated_name_collision:"+__d.masterName);var c=app.project.items.addComp(__d.masterName,__d.width,__d.height,__d.pixelAspect,__d.duration,__d.frameRate);c.comment=__owner();c.motionBlur=false;c.shutterAngle=0;var bg=c.layers.addSolid(__d.backgroundColor,__d.generatedPrefix+"BACKGROUND",__d.width,__d.height,__d.pixelAspect,__d.duration);bg.startTime=0;bg.inPoint=0;bg.outPoint=__d.duration;bg.locked=true;return {ok:true,operation:"create_master",masterCompItemIndex:__idx(c),masterCompName:c.name,backgroundLayer:{index:bg.index,name:bg.name},postVerification:{ok:c.numLayers===1&&c.duration===__d.duration}};`; }

function validate(name, args) {
  const shared = ["expectedProjectFile","generatedPrefix","autoCheckpoint","checkpointLabel","idempotencyKey","idempotencyScope","verifyAfter"];
  const cp = shared.slice(2); const strip = {...args}; cp.forEach((k)=>delete strip[k]);
  let d;
  if(name===TOOL_NAMES[0]){d=common(strip,[...shared.slice(0,2),"sourceCompItemIndex","expectedSourceCompName","generatedRootName","audioMode"]);const audioMode=strip.audioMode===undefined?"preserve":strip.audioMode;if(!["preserve","mute"].includes(audioMode))fail("audioMode must be preserve or mute.");Object.assign(d,{sourceCompItemIndex:optionalIndex(strip.sourceCompItemIndex,"sourceCompItemIndex"),expectedSourceCompName:text(strip.expectedSourceCompName,"expectedSourceCompName",180),generatedRootName:generated(strip.generatedRootName,d.generatedPrefix,"generatedRootName"),audioMode,eventToken:text(strip.generatedRootName,"generatedRootName",180).replace(d.generatedPrefix,"").replace(/[^A-Za-z0-9_-]/g,"_")});d.ownerRootName=d.generatedRootName;return {data:d,script:cloneScript(d)};}
  if(name===TOOL_NAMES[1]){d=common(strip,[...shared.slice(0,2),"rootCompItemIndex","expectedRootCompName","targetDuration","introDuration"]);Object.assign(d,{rootCompItemIndex:optionalIndex(strip.rootCompItemIndex,"rootCompItemIndex"),expectedRootCompName:generated(strip.expectedRootCompName,d.generatedPrefix,"expectedRootCompName"),targetDuration:num(strip.targetDuration,"targetDuration",0.1),introDuration:num(strip.introDuration,"introDuration",0)});d.ownerRootName=d.expectedRootCompName;if(d.introDuration>=d.targetDuration)fail("introDuration must be below targetDuration.");return {data:d,script:extendScript(d)};}
  if(name===TOOL_NAMES[2]){d=common(strip,[...shared.slice(0,2),"rootCompItemIndex","expectedRootCompName","masterCompName","replacements"]);const reps=strip.replacements;if(!Array.isArray(reps)||reps.length>40)fail("replacements must contain at most 40 entries.");Object.assign(d,{rootCompItemIndex:optionalIndex(strip.rootCompItemIndex,"rootCompItemIndex"),expectedRootCompName:generated(strip.expectedRootCompName,d.generatedPrefix,"expectedRootCompName"),masterCompName:generated(strip.masterCompName,d.generatedPrefix,"masterCompName"),replacements:reps.map((x,i)=>{plain(x,`replacements[${i}]`);only(x,["from","to"],`replacements[${i}]`);return {from:text(x.from,`replacements[${i}].from`,180),to:generated(x.to,d.generatedPrefix,`replacements[${i}].to`)};})});d.ownerRootName=d.expectedRootCompName;return {data:d,script:rewriteScript(d)};}
  if(name===TOOL_NAMES[3]){d=common(strip,[...shared.slice(0,2),"rootCompItemIndex","expectedRootCompName","sceneNumber","titleCompName","hero","title","titleWrap","articleChunks"]);if(!Array.isArray(strip.articleChunks)||!strip.articleChunks.length||strip.articleChunks.length>20)fail("articleChunks must contain 1-20 entries.");if(!["suhanov","kurnikov","both"].includes(strip.hero))fail("hero must be suhanov, kurnikov, or both.");Object.assign(d,{rootCompItemIndex:optionalIndex(strip.rootCompItemIndex,"rootCompItemIndex"),expectedRootCompName:generated(strip.expectedRootCompName,d.generatedPrefix,"expectedRootCompName"),sceneNumber:int(strip.sceneNumber,"sceneNumber"),hero:strip.hero,expectedTitleCompName:text(strip.titleCompName,"titleCompName",180),title:text(strip.title,"title",2000),titleWrap:int(strip.titleWrap,"titleWrap"),articleChunks:strip.articleChunks.map((x,i)=>text(x,`articleChunks[${i}]`,30000))});d.ownerRootName=d.expectedRootCompName;return {data:d,script:textScript(d)};}
  if(name===TOOL_NAMES[4]){d=common(strip,[...shared.slice(0,2),"rootCompItemIndex","expectedRootCompName","leafName","generatedLeafName","duration","mediaItems"]);Object.assign(d,{rootCompItemIndex:optionalIndex(strip.rootCompItemIndex,"rootCompItemIndex"),expectedRootCompName:generated(strip.expectedRootCompName,d.generatedPrefix,"expectedRootCompName"),leafName:text(strip.leafName,"leafName",180),generatedLeafName:generated(strip.generatedLeafName,d.generatedPrefix,"generatedLeafName"),duration:num(strip.duration,"duration",0.1),mediaItems:media(strip.mediaItems,"mediaItems",false)});d.ownerRootName=d.expectedRootCompName;return {data:d,script:mediaScript(d)};}
  if(name===TOOL_NAMES[5]){d=common(strip,[...shared.slice(0,2),"finalCompItemIndex","expectedFinalCompName","masterCompItemIndex","expectedMasterCompName","rootCompItemIndex","expectedRootCompName","sourceSceneName","sceneNumber","eventStart","eventDuration","introDuration","rootHasAudio","introEffectCount","mainEffectCount"]);Object.assign(d,{finalCompItemIndex:optionalIndex(strip.finalCompItemIndex,"finalCompItemIndex"),expectedFinalCompName:text(strip.expectedFinalCompName,"expectedFinalCompName",180),masterCompItemIndex:optionalIndex(strip.masterCompItemIndex,"masterCompItemIndex"),expectedMasterCompName:generated(strip.expectedMasterCompName,d.generatedPrefix,"expectedMasterCompName"),rootCompItemIndex:optionalIndex(strip.rootCompItemIndex,"rootCompItemIndex"),expectedRootCompName:generated(strip.expectedRootCompName,d.generatedPrefix,"expectedRootCompName"),sourceSceneName:text(strip.sourceSceneName,"sourceSceneName",180),sceneNumber:int(strip.sceneNumber,"sceneNumber"),eventStart:num(strip.eventStart,"eventStart",0),eventDuration:num(strip.eventDuration,"eventDuration",0.1),introDuration:num(strip.introDuration,"introDuration",0),rootHasAudio:bool(strip.rootHasAudio,"rootHasAudio"),introEffectCount:positiveWhole(strip.introEffectCount,"introEffectCount"),mainEffectCount:positiveWhole(strip.mainEffectCount,"mainEffectCount"),eventToken:text(strip.expectedRootCompName,"expectedRootCompName",180).replace(d.generatedPrefix,"").replace(/[^A-Za-z0-9_-]/g,"_")});d.ownerRootName=d.expectedMasterCompName;return {data:d,script:pairScript(d)};}
  if(name===TOOL_NAMES[6]){d=common(strip,[...shared.slice(0,2),"masterCompItemIndex","expectedMasterCompName","eventId","eventStart","eventDuration","audioItems","captions"]);if(!Array.isArray(strip.captions)||strip.captions.length>8)fail("captions must contain at most 8 entries.");Object.assign(d,{masterCompItemIndex:optionalIndex(strip.masterCompItemIndex,"masterCompItemIndex"),expectedMasterCompName:generated(strip.expectedMasterCompName,d.generatedPrefix,"expectedMasterCompName"),eventId:text(strip.eventId,"eventId",40),eventStart:num(strip.eventStart,"eventStart",0),eventDuration:num(strip.eventDuration,"eventDuration",0.1),audioItems:media(strip.audioItems,"audioItems",true),captions:strip.captions.map((x,i)=>text(x,`captions[${i}]`,400))});d.ownerRootName=d.expectedMasterCompName;return {data:d,script:overlayScript(d)};}
  if(name===TOOL_NAMES[7]){d=common(strip,[...shared.slice(0,2),"sourceCompItemIndex","expectedSourceCompName","sourceLayerName","targetLayerName","expectedEffectCount","masterCompItemIndex","expectedMasterCompName","duration"]);const targetLayerName=strip.targetLayerName===undefined?"CONTROL":strip.targetLayerName;if(!["CONTROL","COLOR"].includes(targetLayerName))fail("targetLayerName must be CONTROL or COLOR.");Object.assign(d,{sourceCompItemIndex:optionalIndex(strip.sourceCompItemIndex,"sourceCompItemIndex"),expectedSourceCompName:text(strip.expectedSourceCompName,"expectedSourceCompName",180),sourceLayerName:text(strip.sourceLayerName,"sourceLayerName",180),targetLayerName,expectedEffectCount:positiveWhole(strip.expectedEffectCount,"expectedEffectCount"),masterCompItemIndex:optionalIndex(strip.masterCompItemIndex,"masterCompItemIndex"),expectedMasterCompName:generated(strip.expectedMasterCompName,d.generatedPrefix,"expectedMasterCompName"),duration:num(strip.duration,"duration",0.1)});d.ownerRootName=d.expectedMasterCompName;return {data:d,script:controlScript(d)};}
  if(name===TOOL_NAMES[8]){d=common(strip,[...shared.slice(0,2),"rootCompItemIndex","expectedRootCompName","expectedDuration","sourceFingerprints","sourceCompItemIndex","sourceCompItemId","expectedSourceCompName","expectedSourceDuration","expectedSourceNumLayers"]);const fingerprints=sourceFingerprints(strip.sourceFingerprints,"sourceFingerprints",false);if(strip.expectedSourceCompName!==undefined){fingerprints.push({itemIndex:optionalIndex(strip.sourceCompItemIndex,"sourceCompItemIndex"),itemId:strip.sourceCompItemId===undefined?null:int(strip.sourceCompItemId,"sourceCompItemId"),name:text(strip.expectedSourceCompName,"expectedSourceCompName",180),duration:num(strip.expectedSourceDuration,"expectedSourceDuration",0.001),numLayers:positiveWhole(strip.expectedSourceNumLayers,"expectedSourceNumLayers"),structureSchema:null,layers:null});}Object.assign(d,{rootCompItemIndex:optionalIndex(strip.rootCompItemIndex,"rootCompItemIndex"),expectedRootCompName:generated(strip.expectedRootCompName,d.generatedPrefix,"expectedRootCompName"),expectedDuration:num(strip.expectedDuration,"expectedDuration",0.1),sourceFingerprints:fingerprints});d.ownerRootName=d.expectedRootCompName;return {data:d,script:auditScript(d),readOnly:true};}
  if(name===TOOL_NAMES[9]){d=common(strip,[...shared.slice(0,2),"rootCompItemIndex","expectedRootCompName"]);Object.assign(d,{rootCompItemIndex:optionalIndex(strip.rootCompItemIndex,"rootCompItemIndex"),expectedRootCompName:generated(strip.expectedRootCompName,d.generatedPrefix,"expectedRootCompName")});d.ownerRootName=d.expectedRootCompName;return {data:d,script:audioScript(d)};}
  if(name===TOOL_NAMES[10]){d=common(strip,[...shared.slice(0,2),"masterName","width","height","pixelAspect","duration","frameRate","backgroundColor"]);if(!Array.isArray(strip.backgroundColor)||strip.backgroundColor.length!==3||strip.backgroundColor.some((x)=>typeof x!=="number"||!Number.isFinite(x)||x<0||x>1))fail("backgroundColor must contain three finite channels from 0 to 1.");Object.assign(d,{masterName:generated(strip.masterName,d.generatedPrefix,"masterName"),width:int(strip.width,"width"),height:int(strip.height,"height"),pixelAspect:num(strip.pixelAspect,"pixelAspect",0.01),duration:num(strip.duration,"duration",0.1),frameRate:num(strip.frameRate,"frameRate",0.1),backgroundColor:strip.backgroundColor.slice()});d.ownerRootName=d.masterName;return {data:d,script:masterScript(d)};}
  fail(`Unsupported slideshow tool: ${name}`);
}

function media(value,label,audioRequired){if(!Array.isArray(value)||value.length>24)fail(`${label} must contain at most 24 entries.`);return value.map((x,i)=>{plain(x,`${label}[${i}]`);only(x,["path","start","duration","sourceIn","audio"],`${label}[${i}]`);const row={path:text(x.path,`${label}[${i}].path`,2048),start:num(x.start,`${label}[${i}].start`,0),duration:num(x.duration,`${label}[${i}].duration`,0.001),sourceIn:num(x.sourceIn,`${label}[${i}].sourceIn`,0),audio:bool(x.audio,`${label}[${i}].audio`)};if(audioRequired&&!row.audio)fail(`${label}[${i}].audio must be true.`);return row;});}
function positiveWhole(value,label){if(!Number.isInteger(value)||value<0)fail(`${label} must be a non-negative integer.`);return value;}

async function execute(name,args,runExtendScriptBody){const prepared=validate(name,args||{});const body=prepared.readOnly?prepared.script:`app.beginUndoGroup(${literal(`AE Agent ${name}`)});try{return (function(){${prepared.script}})();}finally{app.endUndoGroup();}`;const response=await runExtendScriptBody(body);return response.result;}

module.exports = { TOOL_NAMES, createToolDefinitions, validateToolInput: validate, execute };
